//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialErickGenerator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class CEDULAS
    {
        public int ID { get; set; }
        public System.Guid ID_CEDULAS { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        [Display(Name = "LUGAR DE NACIMIENTO:")]
        public string LUGARNACIMIENTO { get; set; }
        [Display(Name = "FECHA DE NACIMIENTO")]
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string SEXO { get; set; }
        public string SANGRE { get; set; }
        [Display(Name = "ESTADO CIVIL")]
        public string ESTADOCIVIL { get; set; }
        public string OCUPACION { get; set; }
        [Display(Name = "FECHA DE EXPIRACION:")]
        public Nullable<System.DateTime> FECHAEXPIRACION { get; set; }
        public string FOTO { get; set; }
        [Display(Name = "COLEGIO ELECTORAL:")]
        public Nullable<int> COLEGIOELECTORAL { get; set; }
        [Display(Name = "UBICACION DEL COLEGIO:")]
        public string UBICACIONCOLEGIO { get; set; }
        [Display(Name = "DIRECCION DE RESIDENCIA:")]
        public string DIRECCIONRECIDENCIA { get; set; }
        public string SECTOR { get; set; }
        public string MUNICIPIO { get; set; }
        [Display(Name = "REGISTRO DE NACIMIENTO")]
        public System.Guid REGISTRONACIMIENTO { get; set; }
        [Display(Name = "CODIGO POSTAL")]
        public Nullable<int> CODIGOPOSTAL { get; set; }
        public Nullable<int> FK_REGISTRO { get; set; }
        public virtual REGISTRO REGISTRO { get; set; }
    }
}
