//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialErickGenerator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class REGISTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRO()
        {
            this.CEDULAS = new HashSet<CEDULAS>();
            this.LOGINE = new HashSet<LOGINE>();
        }
    
        public int ID_REGISTRO { get; set; }
        [Required]
        public string NOMBRECOMPLETO { get; set; }
        public Nullable<int> CEDULARPERSONAL { get; set; }
        [Required]
        public string USUARIO { get; set; }
        [Required]
        public string PASSAWORD { get; set; }
        public string CONFIRMPASSAWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CEDULAS> CEDULAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGINE> LOGINE { get; set; }
    }
}
